#!/usr/bin/env python
import sys
import configparser

from string import Template
from lib import justintv

def main():
    config_file = "config.conf" if (len(sys.argv) == 1) else sys.argv[1]

    config = configparser.ConfigParser({
        'no_streams': '',
        'streams': '',
        'header': '',
        'footer': '',
        'separator': ',&nbsp;',
        'template': '$name'
    })
    try:
        with open(config_file) as f:
            config.read_file(f)
    except IOError:
        sys.exit('Could not open \'{}\'.'.format(config_file))

    # TODO: Error check the config file

    stream_names = config.get('Settings', 'streams')
    streams = justintv.fetch_streams(stream_names)

    output = render(config, streams)

    print(output)

# Given config settings a stream info, render the output to be
# displayed in the subreddit sidebar
def render(config, streams):
    if len(streams) > 0:
        header = config.get('Settings', 'header')
        footer = config.get('Settings', 'footer')
        separator = config.get('Settings', 'separator')

        template = Template(config.get('Settings', 'template'))
        renders = [template.safe_substitute(get_vals(s)) for s in streams]
        body = separator.join(renders)

        return header + body + footer
    else:
        return config.get('Settings', 'no_streams')

# Extract the values from a stream that may be substituted into the
# template
def get_vals(stream):
    return {
        'name': stream['channel']['login'],
        'viewers': stream['channel_count'],
        'title': stream['channel']['title'],
        'icon_tiny': stream['channel']['image_url_tiny'],
        'icon_small': stream['channel']['image_url_small'],
        'icon': stream['channel']['image_url_medium'],
        'icon_large': stream['channel']['image_url_large'],
        'icon_huge': stream['channel']['image_url_huge']
    }

if __name__ == "__main__":
    main()
